2024-05-01 01:35:26,165 ERROR jjuly tried to call UserListView (status: client)
2024-05-01 01:35:26,166 WARNING Not Found: /users/
2024-05-01 01:37:13,064 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:38:54,644 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:40:21,755 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:42:33,952 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:43:33,517 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:44:22,589 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:45:51,670 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:46:16,656 INFO jjuly called OrderCreateView
2024-05-01 01:46:25,139 INFO jjuly called OrderCreateView
2024-05-01 01:46:51,728 INFO OrderForm has no errors
2024-05-01 01:46:51,735 WARNING 2024-08-01 has incorrect format OR 29 is greater than 5
2024-05-01 01:47:24,845 INFO jjuly called OrderCreateView
2024-05-01 01:47:30,181 INFO OrderForm has no errors
2024-05-01 01:47:30,195 INFO Promocode 50discount used by jjuly
2024-05-01 01:47:30,208 INFO FRLuxTrip updated
2024-05-01 01:50:21,378 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:51:10,557 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:51:17,312 INFO OrderDeleteForm has no errors
2024-05-01 01:51:17,341 INFO order number 14 was deleted
2024-05-01 01:51:17,366 INFO jjuly called UserOrderView
2024-05-01 01:52:18,877 ERROR Call failed UserOrderView
2024-05-01 01:52:18,877 WARNING Not Found: /user/5/orders/
2024-05-01 01:53:24,876 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:53:53,729 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:56:22,357 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:57:34,058 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:58:29,244 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 01:58:42,843 INFO jjuly called UserOrderView
2024-05-01 01:59:01,160 INFO jjuly called ReviewCreateView (status: client)
2024-05-01 01:59:29,929 INFO ReviewForm has no errors)
2024-05-01 01:59:29,940 INFO Review 'Nice' was created by jjuly 
2024-05-01 01:59:54,617 ERROR Call failed ReviewEditPage
2024-05-01 01:59:54,618 WARNING Not Found: /user/9/review/2/
2024-05-01 02:00:06,021 INFO jjuly called ReviewEditView (status: client)
2024-05-01 02:00:26,327 INFO ReviewForm has no errors)
2024-05-01 02:00:26,336 INFO Review 'Nice!' was updated by jjuly 
2024-05-01 13:55:31,836 INFO jjuly LOGOUT (status: client)
2024-05-01 14:06:02,738 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 14:08:11,303 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 14:08:16,815 INFO rrandom LOGOUT (status: client)
2024-05-01 14:10:11,884 INFO Registration form has no errors
2024-05-01 14:10:12,176 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py", line 28, in post
    user.save()
  File "C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\models.py", line 20, in save
    raise ValidationError("Error while creating user")
django.core.exceptions.ValidationError: ['Error while creating user']
2024-05-01 14:11:01,947 WARNING Registration form is invalid
2024-05-01 14:11:17,383 INFO Registration form has no errors
2024-05-01 14:11:17,633 INFO dnoal REGISTER (status: client)
2024-05-01 14:13:42,439 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\models.py changed, reloading.
2024-05-01 14:13:43,006 INFO Watching for file changes with StatReloader
2024-05-01 14:14:09,288 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\models.py changed, reloading.
2024-05-01 14:14:09,749 INFO Watching for file changes with StatReloader
2024-05-01 14:14:45,881 INFO Watching for file changes with StatReloader
2024-05-01 14:26:42,694 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\models.py changed, reloading.
2024-05-01 14:26:43,299 INFO Watching for file changes with StatReloader
2024-05-01 14:27:19,673 INFO Watching for file changes with StatReloader
2024-05-01 14:27:49,132 ERROR Call failed ReviewEditPage
2024-05-01 14:27:49,133 WARNING Not Found: /user/9/review/2/
2024-05-01 14:27:59,717 INFO dnoal called OrderCreateView
2024-05-01 14:28:13,498 INFO OrderForm has no errors
2024-05-01 14:28:13,505 ERROR 2024-04-30 is in incorrect format
2024-05-01 14:28:13,531 ERROR Internal Server Error: /tour/2/order/create/
Traceback (most recent call last):
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py", line 238, in post
    order = Order.objects.create(user=request.user, tour=tour, amount=amount, price=amount * tour.price, departure_date=departure_date)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\models.py", line 113, in save
    raise ValidationError("Error while creating order (Check departure date!)")
django.core.exceptions.ValidationError: ['Error while creating order (Check departure date!)']
2024-05-01 14:28:44,785 INFO OrderForm has no errors
2024-05-01 14:28:44,786 ERROR 2024-05-02 is in incorrect format
2024-05-01 14:28:44,806 ERROR Internal Server Error: /tour/2/order/create/
Traceback (most recent call last):
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py", line 238, in post
    order = Order.objects.create(user=request.user, tour=tour, amount=amount, price=amount * tour.price, departure_date=departure_date)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\models.py", line 113, in save
    raise ValidationError("Error while creating order (Check departure date!)")
django.core.exceptions.ValidationError: ['Error while creating order (Check departure date!)']
2024-05-01 14:29:10,638 INFO OrderForm has no errors
2024-05-01 14:29:10,658 INFO PTChipTrip updated
2024-05-01 14:29:10,679 INFO dnoal called SpecificOrderView
2024-05-01 14:29:20,211 INFO OrderDeleteForm has no errors
2024-05-01 14:29:20,232 INFO order number 15 was deleted
2024-05-01 14:29:20,245 INFO dnoal called UserOrderView
2024-05-01 14:29:32,850 INFO dnoal called OrderCreateView
2024-05-01 14:29:48,072 INFO OrderForm has no errors
2024-05-01 14:29:48,073 WARNING 20 is greater than 18
2024-05-01 14:29:58,862 INFO dnoal called OrderCreateView
2024-05-01 14:30:03,287 INFO OrderForm has no errors
2024-05-01 14:30:03,308 INFO PTChipTrip updated
2024-05-01 14:30:03,324 INFO dnoal called SpecificOrderView
2024-05-01 14:30:11,528 INFO dnoal called UserOrderView
2024-05-01 14:30:45,387 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 14:30:45,971 INFO Watching for file changes with StatReloader
2024-05-01 14:32:09,608 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 14:32:10,074 INFO Watching for file changes with StatReloader
2024-05-01 14:32:38,300 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 14:32:38,737 INFO Watching for file changes with StatReloader
2024-05-01 14:33:15,186 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 14:33:15,629 INFO Watching for file changes with StatReloader
2024-05-01 14:33:30,853 INFO dnoal called OrderCreateView
2024-05-01 14:33:44,388 INFO OrderForm has no errors
2024-05-01 14:33:44,401 INFO Promocode 10discount used by dnoal
2024-05-01 14:33:44,429 INFO NRBudTrip updated
2024-05-01 14:33:44,446 INFO dnoal called SpecificOrderView
2024-05-01 14:34:05,596 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 14:34:06,051 INFO Watching for file changes with StatReloader
2024-05-01 14:36:09,316 INFO C:\253504_Vilkina_4\IGI\LR5\django_lab5\touragency\views.py changed, reloading.
2024-05-01 14:36:09,800 INFO Watching for file changes with StatReloader
2024-05-01 14:38:49,400 INFO dnoal called SpecificOrderView
2024-05-01 14:38:53,499 INFO dnoal called UserOrderView
2024-05-01 14:39:12,916 INFO dnoal called SpecificOrderView
2024-05-01 14:39:14,629 INFO dnoal called SpecificOrderView
2024-05-01 14:39:21,609 INFO dnoal called UserOrderView
